[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

  [[redirects]]
    from = "/"
    to = "https://well-made.uk"
    status = 301
  [[redirects]]
    from = "/index"
    to = "https://well-made.uk"
    status = 301
  [[redirects]]
    from = "/index/"
    to = "https://well-made.uk"
    status = 301
